# Generated by Django 3.1 on 2021-06-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='date_of_birth',
            field=models.CharField(default=str, max_length=50),
            preserve_default=False,
        ),
    ]
