# Generated by Django 3.1 on 2021-06-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210610_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='percent',
            field=models.FloatField(default=float),
            preserve_default=False,
        ),
    ]
