# Generated by Django 3.1 on 2021-06-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_studentresult_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
