# Generated by Django 3.1 on 2021-06-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210610_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='grade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='percent',
            field=models.FloatField(null=True),
        ),
    ]
