# Generated by Django 3.1 on 2021-06-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210610_0620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stu_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField()),
            ],
        ),
    ]
