# Generated by Django 3.1 on 2021-06-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_stu_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='web.stu_class'),
        ),
    ]
